#!/usr/bin/env bash
# sync-shared.sh — copy shared/mailbox/*.mjs into the pi extension as a
# GENERATED bundle so the plugin directory stays self-contained
# (cp -r plugins/session-messaging ~/.pi/agent/extensions/ just works).
#
# Run from repo root after touching shared/mailbox/*.mjs.

set -euo pipefail
cd "$(dirname "$0")/.."

SRC=shared/mailbox
DST=plugins/session-messaging/src/shared

mkdir -p "$DST"
for f in "$SRC"/*.mjs; do
	name=$(basename "$f")
	{
		echo "// GENERATED from shared/mailbox/$name — run scripts/sync-shared.sh after editing."
		echo "// Do not edit this file directly."
		echo
		cat "$f"
	} > "$DST/$name"
	echo "synced $name"
done

# checksum so drift is detectable
(cd "$SRC" && sha256sum *.mjs) > "$DST/.checksums"
echo "wrote $DST/.checksums"
